### ISSUE TITLE
Releas a version to make it work with stable configuration on composer.

### ISSUE THREAD

**Issue by sebathi** [fruppel/yii2-googlecharts#2]
composer require "fruppel/yii2-googlecharts" "*"

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package fruppel/yii2-googlecharts could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by fruppel** [comment]
I made a release (v1.0). Could you check again please?
