### ISSUE TITLE
A automatic way to load packages

### ISSUE THREAD

**Issue by marcelodeandrade** [fruppel/yii2-googlecharts#5]
Recently i am needed load packages and i can't load them statically for project reasons. No way to load the packages from a dynamically way?

**Comment by fruppel** [comment]
Hi, can you give me an example or maybe show me another project where packages can be loaded dynamically? Maybe I can add that feature, but at the moment I am not sure if I understood what you mean.

**Comment by marcelodeandrade** [comment]
For example, i need load the package *map* for create a chart using [map visualization](https://developers.google.com/chart/interactive/docs/gallery/map) and i can't load the package map together the [package 'corechart'](https://github.com/fruppel/yii2-googlecharts/blob/master/GoogleCharts.php) in line 44. I can not use statically because the project is distributed and loaded dependencies centrally.

**Comment by fruppel** [comment]
You don't have to load "corechart". Just overwrite $packages when you initialise your widget and load every other package, like "map". For example:

    <?= GoogleCharts::widget([
        'visualization' => 'Map',
        'packages' => 'map',
        'data' => ...
        'options' => ...

and that should translate to the following JS code:

    google.load('visualization', '1', { 'packages': ['map'] });
    google.setOnLoadCallback(drawChart_XYZ);

    function drawChart_XYZ() {
        var data = ....
        var options = ....
        var chart = new google.visualization.Map(document.getElementById('googlechart_XYZ'));
        chart.draw(data, options);
    }

Isn't this what you need?

**Comment by marcelodeandrade** [comment]
Yes! is it! Thank you and my apologies for that question!

**Comment by fruppel** [comment]
No worries. Glad that it helped :-)
