### ISSUE TITLE
Google Charts API has to be changed

### ISSUE THREAD

**Issue by nagyt234** [fruppel/yii2-googlecharts#8]
Is this package died?

Calling Google Charts has to be changed to avoid the following message in browser console:

> A parser-blocking, cross site (i.e. different eTLD+1) script, https://www.google.com/uds/?file=visualization&v=1.0&packages=corechart, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.

Not https://www.google.com/jsapi has to be loaded but https://www.gstatic.com/charts/loader.js. See [https://developers.google.com/chart/interactive/docs/basic_load_libs](https://developers.google.com/chart/interactive/docs/basic_load_libs)

**Comment by fruppel** [comment]
I changed the URL so the notice should be gone => new version 1.2.0

**Comment by nagyt234** [comment]
Could you publish the new version to use with composer? Thanks.

**Comment by fruppel** [comment]
You can already use it with composer. ```composer require fruppel/yii2-googlecharts``` to get the latest version

**Comment by fruppel** [comment]
Sorry, it wasn't updated. Can you try it now? Please let me know if it does not work

**Comment by nagyt234** [comment]
Thank you, it works perfectly, console messages gone.
